cosmos v0.44 support
hukkinj1/cosmospy pull request #28
Opened 2021-12-24 12:21 UTC by ctrl-Felix

add cosmos v0.44 support

2021-12-25 21:46 UTC, czarcas7ic reviewed
This fixed pushing txs to the new endpoint, tysm for this

2021-12-25 21:56 UTC, czarcas7ic commented
But also to note, I had to change one line under get_pushable command

```
        return json.dumps(
           # {"jsonrpc": "2.0", "id": 1, "method": self._sync_mode, "params": {"tx": tx_b64}}
           { "tx_bytes": tx_b64, "mode": "BROADCAST_MODE_SYNC"}
```

2021-12-25 23:12 UTC, ctrl-Felix commented
> I had to change one line under get_pushable command

Wasn't it working like it was there? Because I submitted transactions like this

2021-12-25 23:26 UTC, hukkin requested changes
Thanks a lot!

I'm not yet able to have a good look unfortunately but here's my first drive-by review.

A couple questions:
- where did you get the `.proto` files?
- are all the `.proto` files strictly needed? Is this the smallest set that works?
- what command did you run to generate `.py` files from the `.proto` files?

2021-12-25 23:26 UTC, hukkin commented on README.md
> +r = tx.broadcast(url=rpc_url)
I don't really want this API or the `requests` dependency. Cosmospy is not a networking library.

2021-12-25 23:26 UTC, hukkin commented on README.md
> +r = requests.post(rpc_url, data=pushable_tx)
Let's stick to `httpx` here.

2021-12-25 23:26 UTC, hukkin commented on pyproject.toml
> +    "google >= 3.0.0",
where is `google` dependency used? Do we really need it?

2021-12-25 23:26 UTC, hukkin commented on src/cosmospy/_transaction.py
> +from cosmospy._typing import SyncMode
`typing` module should remain public API. (no underscore prefix)

2021-12-25 23:26 UTC, hukkin commented on src/cosmospy/_transaction.py
> +        _pubkey = pubkey.PubKey()
There shouldn't be a reason to use private variables inside the function scope (applies to other methods too)

2021-12-25 23:26 UTC, hukkin commented on src/cosmospy/_typing.py
> +print(sys.version_info)
This should be removed

2021-12-25 23:26 UTC, hukkin commented on src/cosmospy/_typing.py
> +# Valid transaction broadcast modes for the TX endpoint of the
`POST /cosmos/tx/v1beta1/txs` endpoint

2021-12-25 23:30 UTC, hukkin commented
> > I had to change one line under get_pushable command

> Wasn't it working like it was there? Because I submitted transactions like this

I'm fairly sure @czarcas7ic is correct here. Based on [swagger docs](https://v1.cosmos.network/rpc/v0.42.6) of the `POST /cosmos/tx/v1beta1/txs` endpoint.

2021-12-26 01:18 UTC, czarcas7ic commented
> > I had to change one line under get_pushable command
> 
> Wasn't it working like it was there? Because I submitted transactions like this

Also see https://docs.cosmos.network/master/core/proto-docs.html#cosmos-tx-v1beta1-service-proto

2021-12-26 09:56 UTC, ctrl-Felix commented
> > > I had to change one line under get_pushable command
> 
> > Wasn't it working like it was there? Because I submitted transactions like this
> 
> I'm fairly sure @czarcas7ic is correct here. Based on [swagger docs](https://v1.cosmos.network/rpc/v0.42.6) of the `POST /cosmos/tx/v1beta1/txs` endpoint.

I think it just depends if you use the API or RPC. If you want to use it with the RPC endpoint it works with the way the library did it. If you want t osubmit it to the API you need the change @czarcas7ic made

2021-12-26 10:04 UTC, ctrl-Felix commented
> Thanks a lot!
> 
> I'm not yet able to have a good look unfortunately but here's my first drive-by review.
> 
> A couple questions:
> 
>     * where did you get the `.proto` files?
> 
>     * are all the `.proto` files strictly needed? Is this the smallest set that works?
> 
>     * what command did you run to generate `.py` files from the `.proto` files?

I took the proto files from cyberpy but I think those are the sames they also used in their js library. I will check if they are all needed. This version is just a really fast adaption because I wanted to provide a fix for everyone using cosmospy (also for me I wasn't able to vroadcast transactions in python anymore)

I took the generated python files also from cybai but you can generate those files with tools like https://github.com/dropbox/mypy-protobuf, I will setup a proper way to generate them also in case of changements. 

Regarding the google dep it is needed as everything relies on google.protobuf and if google or protobuf aren't installed you get the error ```ModuleNotFoundError: No module named 'google.protobuf'```

2021-12-26 11:11 UTC, hukkin commented
> I took the proto files from cyberpy but I think those are the sames they also used in their js library. I will check if they are all needed. 

Thanks. Would be good to know what is `cyberpy`s source for these files instead of blindly copying them.

> Regarding the google dep it is needed as everything relies on google.protobuf and if google or protobuf aren't installed you get the error ModuleNotFoundError: No module named 'google.protobuf'

The `google.protobuf` namespace should be available solely from `protobuf` package. See https://github.com/protocolbuffers/protobuf/tree/master/python where the source code is under `google/protobuf/`.

2022-01-15 22:58 UTC, ctrl-Felix commented
Okay, I have some news regarding the proto files

The proto files are coming from cosmos (ex: https://github.com/cosmos/cosmos-sdk/blob/master/proto/cosmos/base/v1beta1/coin.proto => https://github.com/ctrl-Felix/cosmospy/blob/sdkv0.44/src/cosmospy/proto/coin.proto) 

There are then cli utilities to migrate those protos to python code.

I saw some proto files have been updated on cosmos or have more content. I will update them on my repo too.

2022-01-15 23:04 UTC, ctrl-Felix commented
> The `google.protobuf` namespace should be available solely from `protobuf` package. See https://github.com/protocolbuffers/protobuf/tree/master/python where the source code is under `google/protobuf/`.

I am confused too but it needs both. Check out this thread: https://stackoverflow.com/questions/38680593/importerror-no-module-named-google-protobuf

There is no explanation to this

2022-01-15 23:09 UTC, hukkin commented
> I am confused too but it needs both. Check out this thread: https://stackoverflow.com/questions/38680593/importerror-no-module-named-google-protobuf

Did you try removing the `google` dependency? We don't do `import google`, the autogenerated files do `from google.protobuf import *`. I don't think we need the dependency.

2022-01-15 23:13 UTC, hukkin commented
> Okay, I have some news regarding the proto files

I think this may be the best source for the proto files https://buf.build/cosmos/cosmos-sdk/

What we need is
- the minimal set of proto files that we need for `cosmospy` to work (downloaded from the resource above)
- the command to autogenerate Python

I cannot accept a PR with autogenerated files that I can not verify/reproduce myself.

2022-01-15 23:17 UTC, ctrl-Felix commented
I will close the pr anyways and redo it with a new version where the protos are generated from the official ones. This PR is probbaly more a dirty quick fix.

2022-01-15 23:19 UTC, ctrl-Felix commented
> > I am confused too but it needs both. Check out this thread: https://stackoverflow.com/questions/38680593/importerror-no-module-named-google-protobuf
> 
> Did you try removing the `google` dependency? We don't do `import google`, the autogenerated files do `from google.protobuf import *`. I don't think we need the dependency.

ah yeah, you're right. Google is the one which isn't needed.

2022-01-15 23:28 UTC, hukkin commented
BTW, here's the docs for compiling Python from `.proto` https://developers.google.com/protocol-buffers/docs/pythontutorial#compiling-your-protocol-buffers

Here's a link to download the (currently) latest `protoc` binaries https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.3

2022-02-13 18:25 UTC, ctrl-Felix commented
I have some problems with converting the proto files to python files. AS Example:
Coin.proto looks like this on cyberpy https://github.com/SaveTheAles/cyberpy/blob/master/cyberpy/interfaces/coin_pb2.py
My converted version looks like this https://github.com/ctrl-Felix/cosmospy/blob/master/src/cosmospy/generated/coin_pb2.py

2022-04-27 08:48 UTC, closed without merging